;; the values wrapped with {{}} will be filled in automatically

[global]

Name			= {{modName}}
Description		= {{modDescription}}
DllName			= {{modName}}
LocaleFolder	= {{modName}}
ModFolder		= {{modName}}
ModVersion      = {{modVersion}}
PatcherUrl		=

;; //////////////////////////////////////////////////////////////////
;; List of archives to load for this MOD order is important
;; The first Archives registered will be scanned for files first

ArchiveFile_1= {{modName}}Data.sga
;; ArchiveFile_2= InsectData.sga
;; ArchiveFile_3= ICData.sga

;; allows using additonal scenarios or something
CompatableMod_1 = IC
